### ISSUE TITLE
 No default constructor for entity

### ISSUE THREAD

**Issue by pgprasad** [oktadeveloper/spring-boot-microservices-example#12]
When Iam trying to start the beer-catalog-service, I keep getting this below error. Would appreciate your help on this.

2018-04-13 18:06:20.415 ERROR 25728 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:800) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:781) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at com.example.beercatalogservice.BeerCatalogServiceApplication.main(BeerCatalogServiceApplication.java:25) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_162]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.0.1.RELEASE.jar:2.0.1.RELEASE]
**Caused by: org.springframework.orm.jpa.JpaSystemException: No default constructor for entity:  : com.example.beercatalogservice.Beer; nested exception is org.hibernate.InstantiationException: No default constructor for entity:  : com.example.beercatalogservice.Beer**
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:314) ~[spring-orm-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:225) ~[spring-orm-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:527) ~[spring-orm-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61) ~[spring-tx-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242) ~[spring-tx-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:153) ~[spring-tx-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135) ~[spring-data-jpa-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61) ~[spring-data-commons-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at com.example.beercatalogservice.$Proxy122.findAll(Unknown Source) ~[na:na]
	at com.example.beercatalogservice.BeerInitializer.run(BeerCatalogServiceApplication.java:67) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:797) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	... 10 common frames omitted
**Caused by: org.hibernate.InstantiationException: No default constructor for entity:  : com.example.beercatalogservice.Beer**
	at org.hibernate.tuple.PojoInstantiator.instantiate(PojoInstantiator.java:85) ~[hibernate-core-5.2.16.Final.jar:5.2.16.Final]
	at org.hibernate.tuple.PojoInstantiator.instantiate(PojoInstantiator.java:105) ~[hibernate-core-5.2.16.Final.jar:5.2.16.Final]
	at org.hibernate.tuple.entity.AbstractEntityTuplizer.instantiate(AbstractEntityTuplizer.java:673) ~[hibernate-core-5.2.16.Final.jar:5.2.16.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.instantiate(AbstractEntityPersister.java:4774) ~[hibernate-core-5.2.16.Final.jar:5.2.16.Final]
	at org.hibernate.internal.SessionImpl.instantiate(SessionImpl.java:1625) ~[hibernate-core-5.2.16.Final.jar:5.2.16.Final]
	at org.hibernate.internal.SessionImpl.instantiate(SessionImpl.java:1609) ~[hibernate-core-5.2.16.Final.jar:5.2.16.Final]
	at org.hibernate.loader.Loader.instanceNotYetLoaded(Loader.java:1664) ~[hibernate-core-5.2.16.Final.jar:5.2.16.Final]
	at org.hibernate.loader.Loader.getRow(Loader.java:1562) ~[hibernate-core-5.2.16.Final.jar:5.2.16.Final]
	at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:732) ~[hibernate-core-5.2.16.Final.jar:5.2.16.Final]
	at org.hibernate.loader.Loader.processResultSet(Loader.java:991) ~[hibernate-core-5.2.16.Final.jar:5.2.16.Final]

**Comment by mraible** [comment]
My guess is you're running this from your IDE and you don't have a Lombok plugin installed. Does it work when you run `mvn spring-boot:run` from the command line?

**Comment by pgprasad** [comment]
Yes, Iam using Spring Tool Suite IDE. Do we also need Lombok plugin installed for STS IDE?

**Comment by mraible** [comment]
Yes, you'll need to configure Lombok for any IDE you use. You can find the instructions for STS at https://projectlombok.org/setup/eclipse.
