### ISSUE TITLE
Edge service is not starting - BindException

### ISSUE THREAD

**Issue by pgprasad** [oktadeveloper/spring-boot-microservices-example#13]
Run eureka-service http://localhost:8761 - started
Run beer-catalog-service http://localhost:8080/beers - could able to see the list
Run edge-service ; Iam not able to start the edge-service, seeing the below exception. Here, Iam using port 8082.
Any help would be appreciated.

2018-04-17 17:29:34.284  INFO 812 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_EDGE-SERVICE/HFFF014134.us:edge-service: registering service...
2018-04-17 17:29:34.310 ERROR 812 --- [           main] o.apache.catalina.core.StandardService   : Failed to start connector [Connector[HTTP/1.1-8080]]

org.apache.catalina.LifecycleException: Failed to start component [Connector[HTTP/1.1-8080]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167) ~[tomcat-embed-core-8.5.29.jar:8.5.29]

	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at com.example.edgeservice.EdgeServiceApplication.main(EdgeServiceApplication.java:29) [classes/:na]
Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1020) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	... 13 common frames omitted
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_162]
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:591) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1018) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	... 14 common frames omitted

2018-04-17 17:29:34.321  INFO 812 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2018-04-17 17:29:34.327  WARN 812 --- [ost-startStop-1] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [spring.cloud.inetutils] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 
2018-04-17 17:29:34.434  INFO 812 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-04-17 17:29:34.437 ERROR 812 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

The Tomcat connector configured to listen on port 8080 failed to start. The port may already be in use or the connector may be misconfigured.

Action:

Verify the connector's configuration, identify and stop any process that's listening on port 8080, or configure this application to listen on another port.

**Comment by mraible** [comment]
The error says you already have something running on 8080, but the edge-service should be running on 8081. I'd suggest using something like [fkill](https://github.com/sindresorhus/fkill-cli) to stop any processes running on 8080 or 8081. Sometimes `killall java` will work too.
